[workspace]
members = ["blinky", "ttgo_blinky", "ssd1306", "ttgo_ssd1306"]
default-members = []
resolver = "3"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"
