[package]
name = "sx127x_rs"
version = "0.1.0"
edition = "2024"
keywords = ["embedded-hal", "sx127x", "lora"]
license = "MIT"

[dependencies]
sx127x_rs_driver = { version = "0.1.0", path = "../sx127x_rs_driver" }
sx127x_rs_lora = { version = "0.1.0", path = "../sx127x_rs_lora" }
