[package]
name = "sx127x_rs_lora"
version = "0.1.0"
edition = "2024"
keywords = ["embedded-hal", "sx127x", "lora"]

[dependencies]
sx127x_rs_driver = { version = "0.1.0", path = "../sx127x_rs_driver" }
